apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 599694555833.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 599694555833.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
